import { NgModule } from '@angular/core';
import {
    MatInputModule,
    MatButtonModule,
    MatSidenavModule,
    MatToolbarModule,
    MatListModule,
    MatRadioModule,
    MatButtonToggleModule,
    MatSliderModule,
    MatDialogModule,
    MatIconModule,
    MatSelectModule,
    MatGridListModule,
    MatMenuModule,
    MatProgressSpinnerModule,
    MatTableModule,
    MatCheckboxModule,
    MatPaginatorModule,
    MatSortModule,
    MatChipsModule,
    MatSnackBarModule,
    MatCardModule,
    MatProgressBarModule,
    MatTabsModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSlideToggleModule,
    MatStepperModule,
    MatFormFieldModule,
    MatTooltipModule,
} from '@angular/material';

const materials = [
    MatInputModule,
    MatButtonModule,
    MatSidenavModule,
    MatToolbarModule,
    MatListModule,
    MatRadioModule,
    MatButtonToggleModule,
    MatSliderModule,
    MatDialogModule,
    MatIconModule,
    MatSelectModule,
    MatGridListModule,
    MatMenuModule,
    MatProgressSpinnerModule,
    MatTableModule,
    MatCheckboxModule,
    MatPaginatorModule,
    MatSortModule,
    MatChipsModule,
    MatSnackBarModule,
    MatCardModule,
    MatProgressBarModule,
    MatTabsModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSlideToggleModule,
    MatStepperModule,
    MatFormFieldModule,
    MatTooltipModule
]

@NgModule({
    imports: materials,
    exports: materials
})
export class MaterialModule { }
